version: "3.4"

services:
  
  # sodo-chatbot
  sodo-chatbot:
    container_name: "sodo-chatbot"
    image: sodo/sodo-chatbot
    links:
      - chatbot-mongodb
    ports:
      - 8095:8080
    volumes:
      - .:/opt/WORK_SPACE/export/
      - /opt/logs/:/opt/WORK_SPACE/chatbot/data/log/
    environment:
      SPRING_PROFILES_ACTIVE: ci
      MONGODB_HOST: chatbot-mongodb
      
  #MongoDB
  chatbot-mongodb:
    container_name: "chatbot-mongodb"
    image: mongo:3.4.10
    ports:
     - 27017:27017
    command: mongod --replSet rs0 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
    restart: always
  
  # This configures the MongoDB replicaset  
  chatbot-mongosetup:
    container_name: "chatbot-mongosetup"
    image: mongo:3.4.10
    depends_on:
      - chatbot-mongodb
    links:
      - chatbot-mongodb:chatbot-mongodb
    volumes:
      - ./scripts:/scripts
    environment:
      - MONGODB=chatbot-mongodb
    entrypoint: [ "/bin/bash", "/scripts/mongosetup.sh" ]
