version: "3.4"

services:
  
  # sodo-chatbot
  sodo-chatbot:
    container_name: "sodo-chatbot"
    image: sodo/sodo-chatbot
    links:
      - chatbot-mongodb
      - mysql
    ports:
      - 8080:8080
    volumes:
      - .:/opt/WORK_SPACE/export/
      - /opt/logs/:/opt/WORK_SPACE/chatbot/data/log/
    environment:
      SPRING_PROFILES_ACTIVE: ci
      MONGODB_HOST: chatbot-mongodb
      
  #MongoDB
  chatbot-mongodb:
    container_name: "chatbot-mongodb"
    image: mongo:3.4.10
    ports:
     - 27017:27017
    command: mongod --shardsvr --port 27017 --wiredTigerCacheSizeGB=3 --nojournal --oplogSize 16 --noprealloc --smallfiles
    restart: always
    
   #Mysql
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: bigdata
       MYSQL_USER: root
       MYSQL_PASSWORD: root
