version: "3.4"

services:
  
  # sodo-chatbot
  sodo-chatbot:
    container_name: "sodo-chatbot"
    image: sodo/sodo-chatbot
    links:
      - xmarketing-mongodb
    ports:
      - 8095:8080
    volumes:
      - .:/opt/WORK_SPACE/export/
      - /opt/logs/:/opt/WORK_SPACE/chatbot/data/log/
    environment:
      SPRING_PROFILES_ACTIVE: ci
      MONGODB_HOST: xmarketing-mongodb
      
  #MongoDB
  xmarketing-mongodb:
    container_name: "xmarketing-mongodb"
    image: mongo:3.4.10
    ports:
     - 27018:27018
    command: mongod --replSet rs0 --shardsvr --port 27018 --nojournal --oplogSize 16 --noprealloc --smallfiles
    restart: always
  
  # This configures the MongoDB replicaset  
  xmarketing-mongosetup:
    container_name: "xmarketing-mongosetup"
    image: mongo:3.4.10
    depends_on:
      - xmarketing-mongodb
    links:
      - xmarketing-mongodb:xmarketing-mongodb
    volumes:
      - ./scripts:/scripts
    environment:
      - MONGODB=xmarketing-mongodb
    entrypoint: [ "/bin/bash", "/scripts/mongosetup.sh" ]
